[package]
name = "zen-uniffi"
version = "0.1.2"
edition = "2024"
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
uniffi = { version = "0.29.2", features = ["tokio"] }
serde_json = { workspace = true }
zen-engine = { path = "../../core/engine" }
zen-expression = { path = "../../core/expression" }
zen-tmpl = { path = "../../core/template" }
serde = { workspace = true, features = ["derive"] }
async-trait = "0.1"
tokio = "1.43"

[build-dependencies]
uniffi = { version = "0.29.2", features = ["build"] }
uniffi-bindgen-java = "0.2.1"