#!/usr/bin/env bash
#
# fix-csharp-bindings.sh
#
# Fixes the async callback interface bug in C# bindings generated by uniffi-bindgen-cs.
#
# The generator produces sync interface methods (returning T directly) but the
# calling code uses await + .WaitAsync(), causing compilation errors. This script
# patches the interface method signatures to return Task<T> instead.
#
# Usage: ./fix-csharp-bindings.sh <path-to-zen_uniffi.cs>

set -euo pipefail

if [ $# -ne 1 ]; then
    echo "Usage: $0 <path-to-zen_uniffi.cs>"
    exit 1
fi

FILE="$1"

if [ ! -f "$FILE" ]; then
    echo "Error: File not found: $FILE"
    exit 1
fi

echo "Fixing async callback interfaces in $FILE..."

# Fix ZenCustomNodeCallback.Handle: sync → async (Task<>)
sed -i.bak 's/ZenEngineHandlerResponse Handle(ZenEngineHandlerRequest @key)/Task<ZenEngineHandlerResponse> Handle(ZenEngineHandlerRequest @key)/' "$FILE"

# Fix ZenDecisionLoaderCallback.Load: sync → async (Task<>)
sed -i.bak 's/JsonBuffer? Load(string @key)/Task<JsonBuffer?> Load(string @key)/' "$FILE"

# Clean up backup file
rm -f "${FILE}.bak"

echo "Done. Fixed async interfaces in $FILE"
