name: Miri

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  RUST_BACKTRACE: 1
  RUSTUP_MAX_RETRIES: 10

jobs:
  miri:
    name: cargo miri test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: rustup toolchain install nightly --component miri && rustup default nightly
      - uses: ./.github/actions/setup-rust
        with:
          shared-key: rust-miri
          sccache: 'false'
      - run: cargo miri test --workspace --all-features --locked
        env:
          MIRIFLAGS: -Zmiri-strict-provenance -Zmiri-symbolic-alignment-check -Zmiri-disable-isolation
          RUSTFLAGS: ${{ env.RUSTFLAGS }} -Z randomize-layout
